server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  aop:
    proxy-target-class: true

  #模板引擎配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

# 共有8个级别，按照从低到高为：ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF。
logging:
  config: classpath:log4j2.yml